# Generated by Django 3.0.3 on 2020-08-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
