# Generated by Django 3.0.3 on 2020-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='wmobject',
            fields=[
                ('object_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('object_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('object_rel', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
