# Generated by Django 3.0.3 on 2020-08-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wmobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='wmobject_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_path', models.CharField(blank=True, max_length=300)),
                ('object_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('fk_wmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wmobject')),
            ],
        ),
    ]
