# Generated by Django 3.0.3 on 2020-08-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wmobject_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='lookups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type_code', models.CharField(max_length=200)),
                ('lookup_value_code', models.CharField(max_length=200)),
                ('lookup_value', models.CharField(max_length=200)),
                ('lookup_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
