# Generated by Django 3.0.3 on 2020-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200818_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmobject_details',
            name='object_backout',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='wmobject_details',
            name='object_special',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
