# Generated by Django 3.0.3 on 2020-09-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200818_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='wmobject_attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_type', models.CharField(blank=True, max_length=200, null=True)),
                ('attach_file', models.FileField(upload_to='')),
                ('fk_wmobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wmobject')),
            ],
        ),
    ]
