# Generated by Django 3.0.3 on 2020-09-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wmobject_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmobject_attachments',
            name='attach_file',
            field=models.FileField(upload_to='USDE_Attach'),
        ),
    ]
