# Generated by Django 3.0.3 on 2020-09-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200902_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='attach_lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_value', models.CharField(max_length=200)),
                ('lookup_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wmobject_attachments',
            name='attach_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.attach_lookup'),
        ),
    ]
