# Generated by Django 3.0.3 on 2020-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200902_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookups',
            name='lookup_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
