# Generated by Django 3.0.3 on 2020-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200902_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmobject',
            name='object_dev',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wmobject',
            name='object_qa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wmobject',
            name='object_track',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
