# Generated by Django 3.0.3 on 2020-09-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200904_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmobject',
            options={'ordering': ['object_rel', 'object_id']},
        ),
        migrations.RemoveField(
            model_name='wmobject',
            name='app_imp',
        ),
        migrations.RemoveField(
            model_name='wmobject',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='wmobject',
            name='proc_imp',
        ),
        migrations.RemoveField(
            model_name='wmobject',
            name='resolution',
        ),
        migrations.CreateModel(
            name='wmobject_rel_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_imp', models.CharField(blank=True, max_length=2000, null=True)),
                ('proc_imp', models.CharField(blank=True, max_length=2000, null=True)),
                ('objective', models.CharField(blank=True, max_length=2000, null=True)),
                ('resolution', models.CharField(blank=True, max_length=2000, null=True)),
                ('img1', models.ImageField(height_field=800, upload_to='Rel_Notes', width_field=500)),
                ('img2', models.ImageField(height_field=800, upload_to='Rel_Notes', width_field=500)),
                ('img3', models.ImageField(height_field=800, upload_to='Rel_Notes', width_field=500)),
                ('fk_wmobject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.wmobject')),
            ],
        ),
    ]
