# Generated by Django 3.0.3 on 2020-09-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200905_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img1',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='Rel_Notes', width_field=500),
        ),
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img2',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='Rel_Notes', width_field=500),
        ),
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img3',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='Rel_Notes', width_field=500),
        ),
    ]
