# Generated by Django 3.0.3 on 2020-09-05 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200905_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='fk_wmobject',
            field=models.ForeignKey(default='US63006', on_delete=django.db.models.deletion.CASCADE, to='app.wmobject'),
            preserve_default=False,
        ),
    ]
