# Generated by Django 3.0.3 on 2020-09-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200905_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
    ]
