# Generated by Django 3.0.3 on 2020-09-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200905_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmobject_rel_notes',
            name='fk_wmobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.wmobject'),
        ),
    ]
