# Generated by Django 3.0.3 on 2020-09-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200905_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmobject_rel_notes',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='wmobject_rel_notes',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='wmobject_rel_notes',
            name='img3',
        ),
    ]
