# Generated by Django 3.0.3 on 2020-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200930_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmobject_rel_notes',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
        migrations.AddField(
            model_name='wmobject_rel_notes',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
        migrations.AddField(
            model_name='wmobject_rel_notes',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='Rel_Notes'),
        ),
    ]
