# Generated by Django 3.0.3 on 2020-10-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201003_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmobject',
            name='object_sprint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
