# Generated by Django 3.0.3 on 2021-01-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201019_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookups',
            name='lookup_extns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
